import type { ReactElement } from 'react'
import Layout from '../components/Layout'
import NestedLayout from '../components/NestedLayout'
import type { NextPageWithLayout } from './_app'

const Page: NextPageWithLayout = () => {
  return <p>hello world</p>
}

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      <NestedLayout>{page}</NestedLayout>
    </Layout>
  )
}

export default Page




// import { Inter } from '@next/font/google';
// import Head from 'next/head';
// import Image from 'next/image';
// import styles from '../styles/Home.module.css';
// import Layout from '../components/Layout'
// import NestedLayout from '../components/NestedLayout'


// export default function Page() {
//   return (
//     <div>
//       Hello
//     </div>
//   )
// }

// Page.getLayout = function getLayout(page) {
//   return (
//     <Layout>
//       <NestedLayout>{page}</NestedLayout>
//     </Layout>
//   )
// }

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>JsEigth</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//     </>
//   );
// }
