import { Inter } from '@next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import CathegoryOne from '../components/Buttons/CathegoryOne';
import Like from '../components/Buttons/Like';
import NextOne from '../components/Buttons/NextOne';
import NextTwo from '../components/Buttons/NextTwo';
import InputSearch from '../components/InputSearch';
import styles from '../styles/Home.module.css';
import PersonIcon from '../components/PersonIcon';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>JsEigth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Grupo 08:&nbsp;
            <code className={styles.code}>JsEigth</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        <InputSearch/>
        <div className='flex gap-2 items-center justify-center bg-slate-300 p-[40px] rounded-2xl'>
          <NextOne/>
          <NextTwo/>
          <CathegoryOne/>
          <Like/>
          <PersonIcon/>
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

      </main>
    </>
  );
}
